[window]
decorations = "Buttonless"
option_as_alt = "Both"
padding.x = 8
padding.y = 8
opacity = 0.9

[colors]
transparent_background_colors = true

[font]
normal.family = "SFMono Nerd Font"
size = 12

# Map Cmd 1-8 to tabs, see zellij config
[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\uE000" # 

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\uE001" # 

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\uE002" # 

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\uE003" # 

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\uE004" # 

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\uE005" # 

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\uE006" # 

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\uE007" # 

# Copy selected text to the clipboard
[selection]
save_to_clipboard = true
