tap "jesseduffield/lazygit"
tap "jesseduffield/lazydocker"

# Comand line tools
brew "act"
brew "rbenv"
brew "neovim"
brew "gh"
brew "ripgrep"
brew "gnu-sed"
brew "fd"
brew "fzf"
brew "the_silver_searcher"
brew "jesseduffield/lazygit/lazygit"
brew "jesseduffield/lazydocker/lazydocker"
brew "zellij"
brew "antigen"
brew "diff-so-fancy"
brew "caarlos0/tap/svu"
brew "mcfly"
brew "zoxide"

# App stuff
brew "postgresql"
brew "yarn"
brew "imagemagick"
brew "ffmpeg"
