customCommands:
  - key: 'T'
    context: 'global'
    command: 'gh start "{{.Form.Story}}"'
    description: 'Start new story (gh start)'
    prompts:
      - type: 'input'
        title: 'What is the story name?'
        key: 'Story'
        initialValue: ''
  - key: 'F'
    context: 'global'
    command: 'git commit -a --amend --no-edit && git push -f'
    description: 'Amend and force push (gfup)'
  - key: 'O'
    context: 'global'
    command: 'gh pr view --web'
    description: 'Open current PR'
  - key: 'B'
    context: 'global'
    command: 'git bump {{.Form.Version}}'
    description: 'Bump version and create release (git bump)'
    prompts:
      - type: 'menu'
        title: 'Enter version type (major, minor, patch) '
        key: 'Version'
        options:
          - value: 'patch'
          - value: 'minor'
          - value: 'major'
